export const dummydata = [
  {
    newsIndex: 1,
    newsTitle: "[단독] 檢, 민주연구원 압수수색으로 '당직자 명단' 확보",
    newsContent:
      "옛 통일교인 세계평화통일가정연합과 접점이 확인돼 야권으로부터 퇴진 요구를 받아온 야마기와 다이시로 일본 경제재생담당상이 결국 사퇴했습니다.\n",
    newsCategory: "정치",
    newsWriter: "김광민",
    newsRegdate: "2022-10-20",
    newsProvider: "YTN",
    "": null,
  },
  {
    newsIndex: 2,
    newsTitle: "한동훈 술자리",
    newsContent:
      "옛 통일교인 세계평화통일가정연합과 접점이 확인돼 야권으로부터 퇴진 요구를 받아온 야마기와 다이시로 일본 경제재생담당상이 결국 사퇴했습니다.\n",
    newsCategory: "정치",
    newsWriter: "박우빈",
    newsRegdate: "2022-10-21",
    newsProvider: "조선일보",
    "": null,
  },
  {
    newsIndex: 3,
    newsTitle: "국회 과방위, 구글코리아 사장 위증 혐의로 고발 의결",
    newsContent:
      "옛 통일교인 세계평화통일가정연합과 접점이 확인돼 야권으로부터 퇴진 요구를 받아온 야마기와 다이시로 일본 경제재생담당상이 결국 사퇴했습니다.\n",
    newsCategory: "경제",
    newsWriter: "문재현",
    newsRegdate: "2022-10-22",
    newsProvider: "중앙일보",
    "": null,
  },
  {
    newsIndex: 4,
    newsTitle: "민주당, 尹 시정연설 불참...",
    newsContent:
      "옛 통일교인 세계평화통일가정연합과 접점이 확인돼 야권으로부터 퇴진 요구를 받아온 야마기와 다이시로 일본 경제재생담당상이 결국 사퇴했습니다.\n",
    newsCategory: "정치",
    newsWriter: "이종현",
    newsRegdate: "2022-10-23",
    newsProvider: "동아일보",
    "": null,
  },
  {
    newsIndex: 5,
    newsTitle: "밤 9시까지 4만2천여 명 확진...1주 전보다 1만 명↑",
    newsContent:
      "옛 통일교인 세계평화통일가정연합과 접점이 확인돼 야권으로부터 퇴진 요구를 받아온 야마기와 다이시로 일본 경제재생담당상이 결국 사퇴했습니다.\n",
    newsCategory: "사회",
    newsWriter: "홍하영",
    newsRegdate: "2022-10-24",
    newsProvider: "한겨레",
    "": null,
  },
  {
    newsIndex: 6,
    newsTitle: "거래소, 코오롱티슈진 상장유지 결정...거래 재개",
    newsContent:
      "옛 통일교인 세계평화통일가정연합과 접점이 확인돼 야권으로부터 퇴진 요구를 받아온 야마기와 다이시로 일본 경제재생담당상이 결국 사퇴했습니다.\n",
    newsCategory: "경제",
    newsWriter: "박영식",
    newsRegdate: "2022-10-25",
    newsProvider: "경향신문",
    "": null,
  },
  {
    newsIndex: 7,
    newsTitle:
      "13개월 영아에 약물 기준치 50배 투여해 숨지게 한 간호사 구속영장",
    newsContent:
      "옛 통일교인 세계평화통일가정연합과 접점이 확인돼 야권으로부터 퇴진 요구를 받아온 야마기와 다이시로 일본 경제재생담당상이 결국 사퇴했습니다.\n",
    newsCategory: "사회",
    newsWriter: "백수현",
    newsRegdate: "2022-10-26",
    newsProvider: "매일경제",
    "": null,
  },
  {
    newsIndex: 8,
    newsTitle: "통일교와 관련' 日 경제재생상 사퇴",
    newsContent:
      "옛 통일교인 세계평화통일가정연합과 접점이 확인돼 야권으로부터 퇴진 요구를 받아온 야마기와 다이시로 일본 경제재생담당상이 결국 사퇴했습니다.\n",
    newsCategory: "국제",
    newsWriter: "고기천",
    newsRegdate: "2022-10-27",
    newsProvider: "한국경제",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
  {
    newsIndex: null,
    newsTitle: "",
    newsContent: "",
    newsCategory: "",
    newsWriter: "",
    newsRegdate: "",
    newsProvider: "",
    "": null,
  },
];
